---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio
  namespace: minio
spec:
  interval: 1h
  timeout: 60s
  url: https://helm.min.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
      version: "*"
  interval: 1h
  values:
    accessKey: insecure
    secretKey: insecure
    persistence:
      enable: false
    buckets:
      - name: example
        policy: public
---
apiVersion: v1
kind: Namespace
metadata:
  name: bucket
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-bucket-secret
  namespace: bucket
type: Opaque
stringData:
  accesskey: insecure
  secretkey: insecure
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Bucket
metadata:
  name: minio-bucket
  namespace: bucket
spec:
  interval: 5m0s
  endpoint: minio.minio.svc.cluster.local:9000
  insecure: true
  secretRef:
    name: minio-bucket-secret
  bucketName: example
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: minio-bucket
  namespace: bucket
spec:
  interval: 5m0s
  prune: true
  path: .
  sourceRef:
    kind: Bucket
    name: minio-bucket
